name: Build

on:
  push:
    paths:
      - "CMakeLists.txt"
      - "src/**"
  pull_request:
    paths:
      - "CMakeLists.txt"
      - "src/**"

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: windows-latest,
              name: "Windows MSVC",
              cc: cl,
              cxx: cl,
              cflags: "",
            }
          - {
              os: windows-latest,
              name: "Windows Clang",
              cc: clang-cl,
              cxx: clang-cl,
            }
          - { os: ubuntu-latest, name: "Linux Clang", cc: clang, cxx: clang++ }
          - { os: ubuntu-latest, name: "Linux GCC", cc: gcc-10, cxx: g++-10 }
          - { os: macos-latest, name: "OS X Clang", cc: clang, cxx: clang++ }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Build
        shell: bash
        run: cd examples; cmake .; cmake --build .
